name: 'cpd_infra'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'cpd_infra'

vars:
  start_year: 2000
  end_year: 2024
  include_ir_no_in_analytical_table: False
  include_arrestee_names_in_analytical_table: False
  unknown_drug_poss_charges:
    - 'POSSESSION OF A CONTROLLED SUBSTANCE'
    - 'POSSESS CONTROLLED SUBSTANCE'
    - 'ATTEMPT POSSESSION OF CONTROLLED SUBSTANCE'
    - 'ATTEMPT POSSESSION OFCONTROLLED SUBSTANCE'
    - 'POSESS CONTROLLED SUBSTANCE'
    - 'ATTEMPT (POSS CONTROLLED SUBSTANCE <15 GR)'
    - 'ATTEMPT (POSS CONTROLLED SUBSTANCE >15 GRAMS)'
    - 'POSSESSION OF OTHER CONTROLLED SUBSTANCE'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
# analysis-paths: ["analyses"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models. 
# These settings can be overridden in the individual model files using the `{{ config(...) }}` macro.

models:
  cpd_infra:
    +materialized: table
