cpd_infra:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}" 
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: ted_work
      port: 5432
