cpd_infra:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ulpgdev03
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}" 
      dbname: cpd_infra_dev
      schema: ted_work
      port: 5432
