name: dbt_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - pip=25.0.1
  - matplotlib=3.10.1
  - pandas=2.2.3
  - sqlalchemy=2.0.39
  - psycopg2=2.9.9
  - dbt-core=1.9.3
  - dbt-postgres=1.9.0
